[project]
name = "nyc-taxi-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "JynMoriarty", email = "jeffrey69140@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=6.1.1",
    "duckdb>=1.5.6",
    "jupyter>=1.1.1",
    "pandas>=3.0.6",
    "plotly>=7.1.0",
    "polars>=1.44.2",
    "pyarrow>=25.0.1",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.1",
]

[project.scripts]
nyc-taxi-analytics = "nyc_taxi_analytics:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
